/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    SettingAdd: typeof import('./src/components/setting/add.vue')['default']
    SettingBase: typeof import('./src/components/setting/base.vue')['default']
    SettingContents: typeof import('./src/components/setting/contents/index.vue')['default']
    SettingEdit: typeof import('./src/components/setting/edit.vue')['default']
  }
}
