/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CodeMirror: typeof import('./src/components/codeMirror.vue')['default']
    Create: typeof import('./src/components/create.vue')['default']
    EditRight: typeof import('./src/components/edit-right.vue')['default']
    ElementBase: typeof import('./src/components/element/base.vue')['default']
    ElementImage: typeof import('./src/components/element/image.vue')['default']
    ElementImageShow: typeof import('./src/components/element/imageShow.vue')['default']
    ElementLine: typeof import('./src/components/element/line.vue')['default']
    ElementLineShow: typeof import('./src/components/element/lineShow.vue')['default']
    ElementRect: typeof import('./src/components/element/rect.vue')['default']
    ElementRectShow: typeof import('./src/components/element/rectShow.vue')['default']
    ElementText: typeof import('./src/components/element/text.vue')['default']
    ElementTextShow: typeof import('./src/components/element/textShow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingAdd: typeof import('./src/components/setting/add.vue')['default']
    SettingBase: typeof import('./src/components/setting/base.vue')['default']
    SettingContents: typeof import('./src/components/setting/contents/index.vue')['default']
    SettingEdit: typeof import('./src/components/setting/edit.vue')['default']
    UtilsColor: typeof import('./src/components/utils/color.vue')['default']
    UtilsColorRange: typeof import('./src/components/utils/color-range.vue')['default']
    UtilsI18n: typeof import('./src/components/utils/i18n.vue')['default']
  }
}
